dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_089
      password: deGNC%!BN4nzlD9X
      role: developer_089
      schema: dbt_fbalseiro
      threads: 1
      type: snowflake
      user: student089
      warehouse: developer_wh_089
    ci:
      account: yl45797.east-us-2.azure
      database: analytics_089
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_089
      schema: dbt_ci # QA/UAT/Etc.
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_089
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_089
      password: deGNC%!BN4nzlD9X
      role: developer_089
      schema: dbt_prod
      threads: 1
      type: snowflake
      user: student089
      warehouse: developer_wh_089
  target: dev
